### ISSUE TITLE
No longer compiles on freebsd

### ISSUE THREAD

**Issue by ncw** [bazil/fuse#295]
From root of source:

```
$ GOOS=freebsd go build -v ./...
bazil.org/fuse
# bazil.org/fuse
./fuse_kernel.go:1011:43: undefined: unix.FALLOC_FL_KEEP_SIZE
./fuse_kernel.go:1012:43: undefined: unix.FALLOC_FL_PUNCH_HOLE
```

Bisect indicates this is the culprit commit 7e3113a7bda759ce75f1962c375674b8ba97f15a by @tv42

**Comment by ncw** [comment]
Another day, another rclone release, but unfortunately this is still broken :-( Might have to drop mount support for freebsd which would be a shame.
